name: Publish to PyPI

on:
    workflow_run:
        workflows: ["pre-commit"]
        # types:
        #     - completed
        # # Убедитесь, что это происходит только для пуша в master
        # branches:
        #     - master
        # conclusion: success

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install build twine bump2version

            - name: Validate commit message
              id: validate-message
              run: |
                  echo "Last commit message: $(git log -1 --pretty=%B)"
                  if [[ "$(git log -1 --pretty=%B)" =~ (patch|minor|major) ]]; then
                    echo "Valid commit message."
                  else
                    echo "Invalid commit message. Please include 'patch', 'minor', or 'major' in the commit message."
                    exit 1
                  fi

            - name: Bump version based on commit message
              run: |
                  LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
                  if [[ "$LAST_COMMIT_MSG" == *"patch"* ]]; then
                    bump2version patch
                  elif [[ "$LAST_COMMIT_MSG" == *"minor"* ]]; then
                    bump2version minor
                  elif [[ "$LAST_COMMIT_MSG" == *"major"* ]]; then
                    bump2version major
                  fi

            - name: Build package
              run: python -m build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: twine upload dist/*
